# DO NOT EDIT THIS FILE!
#
# Python module M__POA generated by omniidl

import omniORB
omniORB.updateModule("M__POA")

# ** 1. Stub files contributing to this module
import projet_idl

# ** 2. Sub-modules

# ** 3. End
